config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  devise_for :users
  get 'movie2s/new'
  
  get 'movie2s/bucket'
  
  get 'movie2s/addInfo'

  get 'pages/home'
  
  get '/newMovie',  :to => 'movie2s#new'
  
  get '/bucketMovie2s', :to => 'movie2s#bucket'

  get '/movie2s/history', to: 'movie2s#history', as: :movie2s_history
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  
  resources :movie1s

  resources :movie_infos

  resources :movies
  
  resources :movie2s do
    collection do
          delete 'destroy_multiple'
          post 'import'
    end
  end
  
  root 'pages#home'

  get 'welcome/index'

end

app/models/movie_info.rb
class MovieInfo < ActiveRecord::Base
end

app/controllers/movie_infos_controller.rb
class MovieInfosController < ApplicationController
  before_action :set_movie_info, only: [:show, :edit, :update, :destroy]

  # GET /movie_infos
  # GET /movie_infos.json
  def index
    @movie_infos = MovieInfo.all
  end

  # GET /movie_infos/1
  # GET /movie_infos/1.json
  def show
  end

  # GET /movie_infos/new
  def new
    @movie_info = MovieInfo.new
  end

  # GET /movie_infos/1/edit
  def edit
  end

  # POST /movie_infos
  # POST /movie_infos.json
  def create
    @movie_info = MovieInfo.new(movie_info_params)

    respond_to do |format|
      if @movie_info.save
        format.html { redirect_to @movie_info, notice: 'Movie info was successfully created.' }
        format.json { render :show, status: :created, location: @movie_info }
      else
        format.html { render :new }
        format.json { render json: @movie_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_infos/1
  # PATCH/PUT /movie_infos/1.json
  def update
    respond_to do |format|
      if @movie_info.update(movie_info_params)
        format.html { redirect_to @movie_info, notice: 'Movie info was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_info }
      else
        format.html { render :edit }
        format.json { render json: @movie_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_infos/1
  # DELETE /movie_infos/1.json
  def destroy
    @movie_info.destroy
    respond_to do |format|
      format.html { redirect_to movie_infos_url, notice: 'Movie info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_info
      @movie_info = MovieInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_info_params
      params.require(:movie_info).permit(:movie_id, :info_type_id, :info)
    end
end

app/helpers/movie_infos_helper.rb
module MovieInfosHelper
end

app/views/movie_infos/_form.html.erb
<%= form_for(@movie_info) do |f| %>
  <% if @movie_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_info.errors.count, "error") %> prohibited this movie_info from being saved:</h2>

      <ul>
      <% @movie_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :info_type_id %><br>
    <%= f.number_field :info_type_id %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_infos/edit.html.erb
<h1>Editing movie_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_info %> |
<%= link_to 'Back', movie_infos_path %>

app/views/movie_infos/index.html.erb
<h1>Listing movie_infos</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Info type</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_infos.each do |movie_info| %>
      <tr>
        <td><%= movie_info.movie_id %></td>
        <td><%= movie_info.info_type_id %></td>
        <td><%= movie_info.info %></td>
        <td><%= link_to 'Show', movie_info %></td>
        <td><%= link_to 'Edit', edit_movie_info_path(movie_info) %></td>
        <td><%= link_to 'Destroy', movie_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie info', new_movie_info_path %>

app/views/movie_infos/new.html.erb
<h1>New movie_info</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_infos_path %>

app/views/movie_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @movie_info.movie_id %>
</p>

<p>
  <strong>Info type:</strong>
  <%= @movie_info.info_type_id %>
</p>

<p>
  <strong>Info:</strong>
  <%= @movie_info.info %>
</p>

<%= link_to 'Edit', edit_movie_info_path(@movie_info) %> |
<%= link_to 'Back', movie_infos_path %>