config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  devise_for :users
  get 'movie2s/new'
  
  get 'movie2s/bucket'
  
  get 'movie2s/addInfo'

  get 'pages/home'
  
  get '/newMovie',  :to => 'movie2s#new'
  
  get '/bucketMovie2s', :to => 'movie2s#bucket'

  get '/movie2s/history', to: 'movie2s#history', as: :movie2s_history
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  
  resources :movie1s

  resources :movie_infos

  resources :movies
  
  resources :movie2s do
    collection do
          delete 'destroy_multiple'
          post 'import'
    end
  end
  
  root 'pages#home'

  get 'welcome/index'

end

app/models/movie2.rb
class Movie2 < ActiveRecord::Base
  has_paper_trail
  #attr_accessible :tt_id,:genre,:bucket
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Movie2.create! row.to_hash
    end
  end
end

app/controllers/movie2s_controller.rb
class Movie2sController < ApplicationController
  before_action :set_movie2, only: [:show, :edit, :update, :destroy]
  require 'open-uri'
  def new
     @title = "Database Management"
     @movie2 = Movie2.new
  end
  def show
     @movie = Movie2.find(params[:id])
   end
   def index
     @movie2s = Movie2.all
   end
   
   def edit
   end
   
   def bucket
     @bucketMovies=Movie2.where.not(imdb: nil).where('bucket=?',params[:bucket]).order("imdb_rating DESC,year DESC").page(params[:page]).per(30)
     @title=params[:bucket]
   end
   
   def update
     respond_to do |format|
       if @movie2.update(movie2_params)
         format.html { redirect_to bucketMovie2s_path(:bucket => @movie2.bucket), notice: 'Movie1 was successfully updated.' }
         format.json { render :show, status: :ok, location: @movie2 }
       else
         format.html { render :edit }
         format.json { render json: @movie2.errors, status: :unprocessable_entity }
       end
     end
   end
   
   def create
      respond_to do |format|
        @movie2 = Movie2.create(movie2_params)
        if @movie2.save
          format.html { redirect_to @movie2, notice: 'Movie1 was successfully created.' }
          format.json { render :show, status: :created, location: @movie2 }
        else
          format.html { render :new }
          format.json { render json: @movie2.errors, status: :unprocessable_entity }
        end
      end
    end
    
    def destroy
      @movie2.destroy
      respond_to do |format|
        format.html { redirect_to :back, :notice => "Movie was successfully destroyed. #{undo_link}" }
        format.json { head :no_content }
      end
    end	
    
    def destroy_multiple
      params[:delete].each do |id|
        Movie2.find(id.to_s).destroy
      end
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Movie2s were successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
    def import
      Movie2.import(params[:file])
      redirect_to root_url, notice: "Movies imported."
    end
    
    def history
      @versions = PaperTrail::Version.order('created_at DESC').page(params[:page])
    end
    
    def undo_link
      view_context.link_to("undo", revert_version_path(@movie2.versions.last), :method => :post)
    end
    
    def addInfo
      @movie2s = Movie2.all
      @movie2s.each do |movie|
         if movie.imdb
           if movie.imdb['data']['runtime']
             movie.update_attribute(:runtime, movie.imdb['data']['runtime']['time'])
           end
            if movie.imdb['data']['best_plot']
             movie.update_attribute(:imdb_plot, movie.imdb['data']['best_plot']['outline'])
           end        
         end
       end
    end
   
   private
     # Use callbacks to share common setup or constraints between actions.
     def set_movie2
       @movie2 = Movie2.find(params[:id])
     end

     # Never trust parameters from the scary internet, only allow the white list through.
     def movie2_params
       params.require(:movie2).permit(:tt_id,:genre,:bucket)
     end
   
end

app/helpers/movie2s_helper.rb
module Movie2sHelper
end

app/views/movie2s/_form.html.erb
<%= form_for(@movie2) do |f| %>
  <% if @movie2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie2.errors.count, "error") %> prohibited this movie2 from being saved:</h2>

      <ul>
      <% @movie2.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bucket %><br>
    <%= f.text_field :bucket %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie2s/addInfo.html.erb
	<%= @movie2s.count %>

app/views/movie2s/bucket.html.erb
<h1><%= @title %></h1>
<div class="column">
	<h4 class="column">Featured Movies</h4>
	<table>
	<%= paginate @bucketMovies %>
	<input type="checkbox" id="selectAll" value="selectAll"> Select / Deselect All<br/><%= form_tag destroy_multiple_movie2s_path, method: :delete do %>
		<tr>
			<th>tt_id</th>
			<th>Title</th>
  		  	<th>Genre</th>
  		  	<th>Bucket</th>
  		  	<th>Year</th>
  		  	<th>IMDB Rating</th>
  		  	<th>Action</th>
		<tr>
    <% @bucketMovies.each do |movie| %>
		<tr>
			<td><%=movie.tt_id%></td>
			<td><%=movie.tt['films'][0]['title']%></td>
		  	<td><%=movie.genre %></td>
		  	<td><%=movie.bucket %></td>
			<td><%=movie.tt['films'][0]['year']%></td>
		<% if (movie.imdb)%>
			<td><%=movie.imdb['data']['rating'].to_s + '/10'%></td>
		<% else %>
			<td><%=""%></td>
		<%end%>
			<td><%= link_to 'Show', movie %>
        		<%= link_to 'Edit', edit_movie2_path(movie) %>
				<%= link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
				<%= check_box_tag "delete[]",movie.id %>
			</td>
		<tr>
    <% end %>
    <%= submit_tag "Delete selected" %>
  	<%end%>
</table>
</div>

<%= paginate @bucketMovies %>

<script>
$('#selectAll').click(function() {
   if (this.checked) {
       $(':checkbox').each(function() {
           this.checked = true;                        
       });
   } else {
      $(':checkbox').each(function() {
           this.checked = false;                        
       });
   } 
});
</script>

app/views/movie2s/edit.html.erb
<h1>Editing movie2</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie2 %> |
<%= link_to 'Back', movie2s_path %>

app/views/movie2s/history.html.erb
<%= link_to 'Home', pages_home_path %>
<div class="container">
  <h1>History</h1>
<table>
	      <tr>
		  <th>Id</th>
		  <th>Title</th>
		  <th>Poster</th>
		  <th>Genre</th>
		  <th>Bucket</th>
		  <th>Action</th>
	  <tr>
    <% @versions.where( event: 'destroy').each do |version| %>
		  <% if Rails.env.production? %>
		  	<% my_object=PaperTrail.serializer.load(version.object.to_json)%>
		  <% else %>
		  <% my_object=PaperTrail.serializer.load(version.object.to_json)%>
		  <%end%>
		  <% movie_0=JSON.load(open("http://api.tanktop.tv/api/1/eyJzZXJ2aWNlX2lkIjoxN30:1XKPst:glE97qRYa7ziwUHZN94AIjt5a3U/movie/"+my_object['tt_id'].to_s )) %>
		  <% movie_1=JSON.load(open("http://www.omdbapi.com/?i=&t="+URI.encode(movie_0['films'][0]['title'])))%>

		<tr>
		<td><%=my_object['id'] %></td>
		<td><%= movie_0['films'][0]['title']%></td>
		<td><%= image_tag(movie_1['Poster'] ) %></td>  
	  	<td><%=my_object['genre'] %></td>
	  	<td><%=my_object['bucket'] %></td>
        <td>
		Destroyed by:<br>
		<% if version.whodunnit && version.whodunnit != 'Guest' %>
		  <% user = User.find_by_id(version.whodunnit) %>
		  <% if user %>
		    <%= user.email %>
		  <% end %>
		<% else %>
		  Guest
		<% end %>
		<br>
		<%= version.created_at%>
		<%= button_to revert_version_path(version) do%>
		  Restore
		<% end %>
	    </td>
		</tr>
    <% end %>
</div>
</table>

app/views/movie2s/index.html.erb
<h1>Listing movie2s</h1>
<%= link_to 'Home', pages_home_path %>

<table>
  <thead>
    <tr>
      <th>Tt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie2s.each do |movie1| %>
      <tr>		  
        <td><%= movie1.id %></td>
	    <td><%= movie1.tt_id %></td>
	  	<td><%= movie1.genre %></td>
	  	<td><%= movie1.bucket %></td>
	  	<td><%= movie1.created_at %></td>
	  	<td><%= movie1.updated_at %></td>		
        <td><%= link_to 'Show', movie1	 %></td>
        <td><%= link_to 'Edit', edit_movie2_path(movie1) %></td>
        <td><%= link_to 'Destroy', movie1, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= check_box_tag("delete[#{movie1.id}]",1) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie2', new_movie2_path %>

app/views/movie2s/new.html.erb
<h1>New movie2</h1>

<%= render 'form' %>

<%= link_to 'Back', movie2s_path %>

app/views/movie2s/show.html.erb
<%uri_tmdb=URI("https://api.themoviedb.org/3/movie/"+@movie.imdb['data']['tconst'].to_s+"?api_key=a0e48169f6d987eb3a6c9a47fcf577ef")%>
<%res_tmdb=Net::HTTP.get_response(uri_tmdb)%>
<% if res_tmdb.code[0]!='4'%>
	<% movie=JSON.load(open(uri_tmdb))%>
	<% if movie['poster_path'] %>
		<% poster_path="http://image.tmdb.org/t/p/w342"+movie['poster_path']%>
	<%else%>
		<% poster_path="http://dummyimage.com/342x513/000/fff&text=No+Poster"%>
	<%end%>
<%else%>
	<% poster_path="http://dummyimage.com/342x513/000/fff&text=No+Poster"%>
<%end%>
<div><%= @movie.tt['films'][0]['title'] %></div>
<div><%= @movie.year %></div>
<div><%= @movie.imdb_rating %></div>
<div><%= image_tag  poster_path%></div>
<div><%= @movie.imdb_plot%></div>
<div><%= @movie.runtime%></div>